### ISSUE TITLE
If 'gitlabci.log_path' is a directory, the server crashes

### ISSUE THREAD

**Issue by Pizmovc** [alesbrelih/gitlab-ci-ls#43]
You can easily reproduce this by creating a directory and using that as the value for this setting and trying to use the language server.

The error you get is a somewhat helpful, but could be a bit more verbose to indicate that the log path is a directory but should be a (non-existing) file instead.

The error message in question:
```
Error: Os { code: 21, kind: IsADirectory, message: "Is a directory" }

Process gitlabci stderr finished
```

**Comment by alesbrelih** [comment]
👌

**Comment by alesbrelih** [comment]
Should be fixed with https://github.com/alesbrelih/gitlab-ci-ls/commit/09b93e58aa5170747755806d986be89f415d0aee 
#hope 😅
