### ISSUE TITLE
Diagnostics and Hover Issue

### ISSUE THREAD

**Issue by halshar** [alesbrelih/gitlab-ci-ls#5]
Hello, as mason support is yet to be added, so below is how I've configured the LSP after installing it through cargo
```lua
-- setup lsp handlers
mason_lspconfig.setup_handlers({
  function(server_name)
    require("lspconfig")[server_name].setup({
      capabilities = capabilities,
      on_attach = on_attach,
      settings = servers[server_name],
      filetypes = (servers[server_name] or {}).filetypes,
    })
  end,
})
require("lspconfig").gitlab_ci_ls.setup({})
```

Facing following issues:
- The hover functionality does not work(tested after removing yaml-language-server yamlls lsp)
- I see `man.lua: "no manual entry for <hovered object like project, ref, etc)`  issue when using hover functionality
- The diagnostics only work when yamlls lsp is enabled else I see nothing

using `NVIM v0.9.5` and `Ubuntu 22.04` through WSL on Windows 11

**Comment by halshar** [comment]
yes, through `:LspInfo` I see the LSP being attached and upon checking the logs I see the error as follows
```
[ERROR][date] .../vim/lsp/rpc.lua:734 "rpc" "/home/<user>/.cargon/bin/gitlab-ci-ls" "stderr" "Error: Error {code: -3, klass: 6, message: \" could not find repository at '/home/<user>'\" }\nthread '<unamed>' panicked at /home/<user>/.cargo/registry/src/index.crates.io-id/lsp-server-0.7.6/src/stdio.rs:28:37:\nreceiver was dropped, failed to send a message: \"SendError(..)\"\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

sorry, this is my work laptop so had to type the error message and I think the above error is due to zscaler :(

I was able to install the LSP server using cargo on my work machine but now that I want to replicate the same issue on my personal machine I'm getting following error:
```bash
   Compiling gitlab-ci-ls v0.10.0
error[E0432]: unresolved import `std::hash::DefaultHasher`
 --> /home/samshal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gitlab-ci-ls-0.10.0/src/gitlab_ci_ls_parser/parser_utils.rs:1:17
  |
1 | use std::hash::{DefaultHasher, Hash, Hasher};
  |                 ^^^^^^^^^^^^^ no `DefaultHasher` in `hash`
  |
  = help: consider importing this struct instead:
          std::collections::hash_map::DefaultHasher

For more information about this error, try `rustc --explain E0432`.
error: could not compile `gitlab-ci-ls` (bin "gitlab-ci-ls") due to previous error
error: failed to compile `gitlab-ci-ls v0.10.0`, intermediate artifacts can be found at `/tmp/cargo-installFEXB5v`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

```

**Comment by alesbrelih** [comment]
Your home machine is also Win/WSL setup?

Also thanks for logs, narrows the problem quite a bit 👍

**Comment by alesbrelih** [comment]
Could you also give me the:

`rustc --version`? 🙏

**Comment by alesbrelih** [comment]
I think I fixed those problems:
1. I assumed LS was being run inside GIT repo.. (assumption is the mother of all f***)
2. added specific hasher to prevent any problems with platform/rust version.

https://github.com/alesbrelih/gitlab-ci-ls/actions/runs/8590864735

If you could be so kind to retry after this is done 🙏

**Comment by halshar** [comment]
Thank you, I thought the issue was with the rust compiler so I updated it to be on the safer side but you had already pushed the fix and the LSP server was installed
```bash
~
❯ rustc --version
rustc 1.77.1 (7cf61ebde 2024-03-27)

~
❯ cargo install gitlab-ci-ls
    Updating crates.io index
     Ignored package `gitlab-ci-ls v0.10.1` is already installed, use --force to override

~
❯
```

**Comment by halshar** [comment]
I'm on my personal machine and I see no errors in the log file but I see following issues:
- I've disabled the yamlls and the gitlab-ci-ls reports basic diagnostics but when I enable yamlls it starts reporting more
- For e.g the gitlab-ci-ls reports diagnostics like duplicate key but when I delete few keys from the set keywords(like image) it reports nothing
- But when yamlls is enabled the same operation starts reporting below errors(copied from trouble.nvim)
   ```
     - Incorrect type. Expected "job_template". yaml-schema: gitlab-ci (0) [1, 7]
     - Matches multiple schemas when only one must validate. yaml-schema: gitlab-ci (0) [1, 7]
   ```
The goto definition for variables works fine and did not test the references functionality

But so far everything is good, and thank you for all your work :)

**Comment by alesbrelih** [comment]
Yeah I use it along with yamlls.

Yamlls validates gitlab file schema (or any other yaml schema), like property keys (image, needs, ..) and my language server adds extra functionality specific for gitlab. So it gets aware of stage definitions, job definitions and then can report diagnostics if you use invalid job name when extending a job. Or if you are using invalid stage or invalid job needs dependency.

+ it adds navigational bonuses like jumping from extend its definition with go to definition (which in my case when we had like 5 gitlab files with a lot of base definitions got handy :D)

Np, I just hope you find value in it :)
