### ISSUE TITLE
Support for multiple caches

### ISSUE THREAD

**Issue by metalinspired** [alesbrelih/gitlab-ci-ls#78]
Hi,

This would be nice to have: https://docs.gitlab.com/ee/ci/caching/index.html#use-multiple-caches

Best regards

**Comment by alesbrelih** [comment]
Hey, could you explain a bit more?

Do you mean autocomplete for project paths? If that is the case I think its better to use:

* VSCode - https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense
* neovim - https://github.com/hrsh7th/cmp-path

Because it is not Gitlab specific 🤔

**Comment by metalinspired** [comment]
Not autocomplete for project paths but for everything that is normally supported under `cache:` but when specify multiple caches as a list.
And also a warning if you specify more than four caches :)

**Comment by metalinspired** [comment]
Considering how I practically gave you no context and that I'm generally terrible in explaining things I could not blame you even if I wanted to :)

Thanks in advance

**Comment by alesbrelih** [comment]
Hey, I've checked this out. I'll implement the diagnostics, but the autocomplete should come from schemastore.

I've created a MR that will fix schemastore for GitlabCI to support multiple caches: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/163020

Lets hope it gets merged :)

**Comment by alesbrelih** [comment]
Added diagnostics: https://github.com/alesbrelih/gitlab-ci-ls/releases/tag/0.21.0. 
Waiting for the MR above to be merged, but will close this issue anyway because I've done what I can on my part

**Comment by alesbrelih** [comment]
Update: It got traction https://gitlab.com/gitlab-org/gitlab/-/merge_requests/163020, should be merged soon :)
